== About Portage 

Portage is a package management system originally created
for and used by Gentoo Linux,and Funtoo Linux among others.

Portage is based on concept of ports collections. Gentoo is 
sometimes referred to as a meta-distribuition due to the 
extremely flexibility of Portage,which makes it operating-system
independent.

The Gentoo is concerned with using Portage to manage other
operating systems,such as BSDs,macOS and Solaris,the most
notable of these implementation is the Gentoo/FreeBSD project.

There is an ongoing effort called the Package Manager Specification
(PMS),which aims to standardise and document the behaviour of
Portage,allowing the ebuild tree and Gentoo system packages 
to be used with alternative package managers such as Paludis 
and pkgcore. Its goal is to specify the exact set of features
and behaviour of package manager and ebuilds,serving as an
authoritative reference for Portage.

== Acessing Portage

Portage is similar to the BSD-style package management known as 
ports,and was originally designed with FreeBSD's ports in mind.
Portage is written in the Python programming language,and is the
main utility that defines Gentoo. Although the system itself is 
known as Portage,it consists of two main parts,the ebuild system
and emerge. The ebuild system takes care of the actual work of 
building and installing packages,while emerge provides an interface
to ebuild: managing an ebuild repository, resolving dependencies 
and similar issues.

Fun fact:
GTK based GUI, Porthole,is available for working for Portage. 
There is also Himerge GUI,which stands for "Haskell interface 
for eMerge".

== Functions Provided

Portage is characterized by its main function: 
compiling from source code the packages the user whishes to install. 
In doing so it allows costumization of compiler and target-application 
options to fit the system's specifications and to user's own whishes.

Functionalities related to system management incluide:

- Allowing parallel package-version installation
- Tacking cross-package dependencies 
- Managing a database of installed packages
     providing a local ebuild repository,and synchronizing of 
      the local Portage tree with remotes repositories. 

- Functionalities related to individual package installation
  include:
     specifying compilation settings for the target machine and 
      choosing packages components.
      
Portage distinguishes between three level of stability in ebuilds:

- Stable
     (e.g., the software works as intended with no 
       known security issues at time of release)
  
- Keyword masked 
     (mainly for packages that have not been sufficiently tested
       on the target system architecture to be considered stable)
       
- Hard masked 
     (Broken or very insecure packages)





== Features
=== Emerge

The emerge command-line tool is the heart of portage. The command is
costumizable with many options and modifiers. The emerge tool is the most
important utility for acessing the features of Portage from commnad line.

The program calculates and manages dependencies,executes ebuilds and
maintains the local Portage tree and database of installed packages.
The compilation settings used by ebuilds can be changed through the CFLAGS
environment variable,based on the specifications of the individual computer
and on the user's desire for optimization. The emerge utility executes 
ebuilds in a sandbox environment.

- sandbox :
          a sandbox is a security mechanism for separating running
          programs,usually in an effor to mitigate system failures
          and/or software vulnerabilities from spreading. It is 
          often used to execute untested or untrusted programs or
          code,possibly from unverfied or untrusted third parties,
          suppliers,users or websites,without risking harm to the
          host machine or operating system. A sandbox typically 
          provides a tightly controlled set of resources for guest
          programs to run in,such as storage and memory scratch 
          space. Network acess,the ability to inspect the host 
          system or read from input devices are usually disallowed
          or heavily restricted. In the sense of providing a highly
          controlled environment, sandboxes may be seen as a specific
          example of virtualization. 

This way the system is protected from software executed by the ebuild and 
resulting binaries are only merged after a sucessfull build and sandboxed
install.

== USE flags


          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          




















